version: "3"

services:
  nodejs:
    image: node:20-alpine
    working_dir: /home/node/app
    ports: 
      - "3000:3000"
      - "3001:3001"
    volumes: 
      - ./microservicio:/home/node/app
    command: npm start

  my_mysql:
    image: mysql:latest
    volumes:
      - ./database/mysql:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_DATABASE: maindb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33067:3306
    expose: 
      - 33067